apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
spec:
  # Balances incoming traffic between the available replicas
  type: LoadBalancer
  selector:
    app: notes-app
  ports:
    - port: 80         # The external port (standard browser default)
      targetPort: 8000 # The internal port where gunicorn is listening