name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    # the deployment that I see in GitHub
    environment:
      name: Production
      url: https://secure-notes-app-flask.onrender.com

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}